obj-$(CONFIG_LGE_DISPLAY_TF10) += tf10/

obj-$(CONFIG_LGE_DISPLAY_AOD_SUPPORTED) += lge_mdss_aod.o
obj-$(CONFIG_LGE_DISPLAY_AOD_WITH_MIPI) += lge_mdss_watch.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi_panel.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_fb.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_sysfs.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_sysfs_imgtune.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mplus.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += notifier/lge_panel_notifier.o
obj-$(CONFIG_LGE_DISPLAY_AMBIENT_SUPPORTED) += ambient/lge_ambient.o
obj-$(CONFIG_LGE_DP_UNSUPPORT_NOTIFY) += lge_dp_notify.o
obj-$(CONFIG_LGE_INTERVAL_MONITOR) += lge_interval_monitor.o
obj-$(CONFIG_LGE_FBCN) += lge_fbcn.o
