# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT5726)         += focaltech_ex_fun.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT5726)         += focaltech_ctl.o
#obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT5726)        += focaltech_flash.o
